# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

sphinx:
  configuration: docs/conf.py

formats: all

build:
  os: ubuntu-22.04
  tools:
    python: '3'

python:
  install:
    - method: setuptools
      path: .
    - requirements: docs/requirements.txt
